use strict;
use warnings;
open(my $fh, '>', '/workspace/restaurant-pdfs/v4/tokyo-kissaten.html') or die $!;
print $fh "<!DOCTYPE html>\n<html lang='en'>\n<head>\n<meta charset='UTF-8'>\n<title>Tokyo Kissaten — Operations Guide</title>\n";
print $fh "<link href='https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght\@0,400;0,700;0,900;1,400&family=Inter:wght\@300;400;500;600;700&display=swap' rel='stylesheet'>\n";
print $fh "<style>\n";
print $fh ":root{--primary:#1a1a3e;--accent:#f5f0e8;--gold:#c8a87a;--text:#2a2a3a;--light:#f9f7f4}\n";
print $fh "*{margin:0;padding:0;box-sizing:border-box}\n";
print $fh "body{font-family:'Inter',sans-serif;color:var(--text);background:#fff;width:210mm;margin:0 auto;font-size:13px;line-height:1.6}\n";
print $fh "h1{font-family:'Playfair Display',serif;font-size:52px;color:#fff;line-height:1.1}\n";
print $fh "h2{font-family:'Playfair Display',serif;font-size:28px;color:var(--primary);border-bottom:3px solid var(--primary);padding-bottom:10px;margin:30px 0 20px}\n";
print $fh "h3{font-family:'Playfair Display',serif;font-size:20px;color:var(--primary);margin:20px 0 10px}\n";
print $fh "h4{font-family:'Inter',sans-serif;font-size:11px;font-weight:700;color:var(--primary);text-transform:uppercase;letter-spacing:2px;margin:15px 0 8px}\n";
print $fh ".cover{background:linear-gradient(135deg,#1a1a3e 0%,#2d2d6e 50%,#0a0a1e 100%);padding:80px 60px;min-height:297mm;display:flex;flex-direction:column;justify-content:center;page-break-after:always}\n";
print $fh ".cover-sub{color:#c8a87a;font-family:'Inter',sans-serif;font-weight:300;font-size:16px;letter-spacing:4px;text-transform:uppercase;margin-bottom:20px}\n";
print $fh ".cover-tagline{color:#c8c8e8;font-size:18px;margin-top:20px;font-style:italic;font-family:'Playfair Display',serif}\n";
print $fh ".cover-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:20px;margin-top:60px}\n";
print $fh ".cs{background:rgba(255,255,255,0.1);border:1px solid rgba(200,168,122,0.3);padding:20px;text-align:center;border-radius:4px}\n";
print $fh ".cs-num{font-size:32px;font-weight:700;color:#c8a87a;font-family:'Playfair Display',serif}\n";
print $fh ".cs-label{font-size:11px;color:#c8c8e8;text-transform:uppercase;letter-spacing:2px;margin-top:5px}\n";
print $fh ".section{padding:40px 50px;page-break-inside:avoid}\n";
print $fh ".recipe-card{background:#fff;border:1px solid #e8e0d4;border-left:5px solid var(--primary);padding:25px;margin:25px 0;border-radius:0 4px 4px 0;page-break-inside:avoid}\n";
print $fh ".recipe-photo{width:100%;height:180px;object-fit:cover;border-radius:4px;margin-bottom:15px}\n";
print $fh ".recipe-meta{display:flex;gap:10px;flex-wrap:wrap;margin:10px 0}\n";
print $fh ".badge{display:inline-block;padding:3px 10px;border-radius:12px;font-size:10px;font-weight:600;text-transform:uppercase;letter-spacing:1px}\n";
print $fh ".badge-temp{background:#1a1a3e;color:#fff}\n";
print $fh ".badge-allergen{background:#f5f0e8;color:#1a1a3e;border:1px solid #1a1a3e}\n";
print $fh ".cost-bar{display:grid;grid-template-columns:repeat(3,1fr);gap:15px;background:#f9f7f4;padding:15px;border-radius:4px;margin:15px 0}\n";
print $fh ".cost-item{text-align:center}\n";
print $fh ".cost-num{font-size:20px;font-weight:700;color:var(--primary);font-family:'Playfair Display',serif}\n";
print $fh ".cost-label{font-size:10px;color:#888;text-transform:uppercase;letter-spacing:1px}\n";
print $fh ".ingredients{columns:2;gap:20px;margin:15px 0}\n";
print $fh ".ing-item{display:flex;justify-content:space-between;padding:4px 0;border-bottom:1px dotted #e0d8cc;font-size:12px;break-inside:avoid}\n";
print $fh ".ing-weight{font-weight:600;color:var(--primary)}\n";
print $fh ".steps ol{padding-left:20px}\n";
print $fh ".steps li{padding:6px 0;font-size:12px;line-height:1.5}\n";
print $fh ".chef-tip{background:linear-gradient(135deg,#1a1a3e,#2d2d6e);color:#fff;padding:15px 20px;border-radius:4px;margin:15px 0;font-size:12px}\n";
print $fh ".chef-tip strong{color:#c8a87a;display:block;margin-bottom:5px;font-size:11px;text-transform:uppercase;letter-spacing:1px}\n";
print $fh ".drink-card{background:#fff;border:1px solid #e8e0d4;padding:20px;margin:20px 0;border-radius:4px;page-break-inside:avoid}\n";
print $fh ".drink-photo{width:100%;height:110px;object-fit:cover;border-radius:4px;margin-bottom:12px}\n";
print $fh ".drink-price{display:inline-block;background:#1a1a3e;color:#c8a87a;padding:5px 15px;border-radius:12px;font-size:14px;font-weight:700;margin:5px 0}\n";
print $fh ".kpi-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:15px;margin:20px 0}\n";
print $fh ".kpi{background:var(--primary);color:#fff;padding:20px;text-align:center;border-radius:4px}\n";
print $fh ".kpi-num{font-size:28px;font-weight:700;color:#c8a87a;font-family:'Playfair Display',serif}\n";
print $fh ".kpi-label{font-size:10px;text-transform:uppercase;letter-spacing:1px;margin-top:5px;color:#c8c8e8}\n";
print $fh ".script-box{background:#f9f7f4;border-left:4px solid #c8a87a;padding:15px 20px;margin:15px 0;font-style:italic;font-size:13px;border-radius:0 4px 4px 0}\n";
print $fh ".script-box cite{display:block;margin-top:8px;font-style:normal;font-size:11px;color:#888;font-weight:600}\n";
print $fh ".timing-grid{display:grid;grid-template-columns:120px 1fr;gap:10px;margin:15px 0}\n";
print $fh ".timing-time{font-weight:700;color:var(--primary);font-size:12px;padding:8px 0;border-bottom:1px solid #e0d8cc}\n";
print $fh ".timing-action{font-size:12px;padding:8px 0;border-bottom:1px solid #e0d8cc}\n";
print $fh ".sn{display:inline-flex;align-items:center;justify-content:center;width:28px;height:28px;border-radius:50%;background:var(--primary);color:#fff;font-weight:700;font-size:12px;margin-right:8px;flex-shrink:0}\n";
print $fh ".step-row{display:flex;align-items:flex-start;margin:10px 0;font-size:13px}\n";
print $fh ".rh{background:linear-gradient(135deg,#1a1a3e,#2d2d6e);color:#fff;padding:30px 50px;margin:30px 0;page-break-inside:avoid}\n";
print $fh ".rh h2{color:#c8a87a;border-color:#c8a87a}\n";
print $fh "table{width:100%;border-collapse:collapse;margin:15px 0;font-size:12px}\n";
print $fh "th{background:var(--primary);color:#fff;padding:8px 12px;text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:1px}\n";
print $fh "td{padding:8px 12px;border-bottom:1px solid #e8e0d4}\n";
print $fh "tr:nth-child(even) td{background:#f9f7f4}\n";
print $fh ".callout{background:#f5f0e8;border:1px solid #c8a87a;border-radius:4px;padding:20px;margin:20px 0}\n";
print $fh ".callout h4{color:#1a1a3e}\n";
print $fh "\@media print{body{width:210mm}.cover{page-break-after:always}}\n";
print $fh "</style>\n</head>\n<body>\n";
close($fh);
print "Header written\n";
